ProEvoCanary.Web/Controllers/ResultsController.cs
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ProEvoCanary.Web.Controllers
{
	public class ResultsController : Controller
	{
		private readonly HttpClient _client;


		public ResultsController(IHttpClientFactory clientFactory)
		{
			_client = clientFactory.CreateClient("API");
		}

		// GET: Results
		public async Task<ActionResult> Update(Guid id)
		{
			var model = JsonConvert.DeserializeObject<Models.ResultsModel>(await _client.GetStringAsync("/api/Event"));
			return View(model);
		}

		[HttpPost]
		public async Task<ActionResult> Update(Models.ResultsModel model)
		{
			var put = await _client.PutAsync("/api/Results", new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"));
			var readAsStringAsync = await put.Content.ReadAsStringAsync();

			var eventId = JsonConvert.DeserializeObject<Guid>(readAsStringAsync);


			return RedirectToAction("Details", "Event", new { id = model.EventId });

		}
	}
}

ProEvoCanary.Web/Views/Results/Update.cshtml
@model ProEvoCanary.Web.Models.ResultsModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Update", "Results", FormMethod.Post))
{
    <div class="row">
        Update result 
    </div>
    @Html.HiddenFor(m => m.ResultId)
    @Html.HiddenFor(m => m.EventId)
    <div class="row">
        <div class="col s6">
            <label>
                @Model.HomeTeam
                @Html.TextBoxFor(m => m.HomeScore, new { @placeholder = "Enter your password" })
            </label>
        </div>
        <div class="col s6">
            <label>
                @Model.AwayTeam
                @Html.TextBoxFor(m => m.AwayScore, new { @placeholder = "Enter your email address" })
            </label>
        </div>

    </div>
    <div class="row">
        <div class="col s12">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Submit
                <i class="material-icons right">send</i>
            </button>
        </div>
    </div>

}