ProEvoCanary.Web/Controllers/RecordsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProEvoCanary.DataAccess.Repositories.Interfaces;
using ProEvoCanary.Web.Models;

namespace ProEvoCanary.Web.Controllers
{
    [AllowAnonymous]
    public class RecordsController : Controller
    {
        private readonly IPlayerRepository _playerRepository;
        private readonly IResultRepository _resultRepository;

        public RecordsController(IPlayerRepository playerRepository, IResultRepository resultRepository)
        {
            _playerRepository = playerRepository;
            _resultRepository = resultRepository;
        }

        public ActionResult HeadToHead()
        {
            var playerList = _playerRepository.GetAllPlayers();
            var model = new ResultsListModel
            {
                PlayerList = playerList.Select(x=> new PlayerModel
                {
	                
                }).ToList()
            };

            return View("HeadToHead", model);
        }

        [HttpGet]
        public JsonResult HeadToHeadResult(int playerOneId, int playerTwoId)
        {
            var playerOneList = _playerRepository.GetAllPlayers();
            var headToHeadRecord = _resultRepository.GetHeadToHeadRecord(playerOneId, playerTwoId);
            var model = new ResultsListModel
            {
                PlayerList = playerOneList.Select(x => new PlayerModel
                {

                }).ToList(),
                PlayerOne = playerOneId,
                PlayerTwo = playerTwoId,
                HeadToHead = new RecordsModel
                {
                    PlayerOneWins = headToHeadRecord.PlayerOneWins,PlayerTwoWins = headToHeadRecord.PlayerTwoWins,
                    Results = headToHeadRecord.Results.Select(x=> new ResultsModel()).ToList(),TotalDraws = headToHeadRecord.TotalDraws,TotalMatches = headToHeadRecord.TotalMatches
                }
            };

            return Json(model);
        }

        public ActionResult HeadToHeadResults(int playerOneId, int playerTwoId)
        {
	        var playerOneList = _playerRepository.GetAllPlayers();
	        var headToHeadRecord = _resultRepository.GetHeadToHeadRecord(playerOneId, playerTwoId);
	        var model = new ResultsListModel
	        {
		        PlayerList = playerOneList.Select(x => new PlayerModel
		        {

		        }).ToList(),
		        PlayerOne = playerOneId,
		        PlayerTwo = playerTwoId,
		        HeadToHead = new RecordsModel
		        {
			        PlayerOneWins = headToHeadRecord.PlayerOneWins,
			        PlayerTwoWins = headToHeadRecord.PlayerTwoWins,
			        Results = headToHeadRecord.Results.Select(x => new ResultsModel()).ToList(),
			        TotalDraws = headToHeadRecord.TotalDraws,
			        TotalMatches = headToHeadRecord.TotalMatches
		        }
	        };

            return View("HeadToHead", model);
        }
    }
}

ProEvoCanary.Web/Views/Shared/_Header.cshtml
<div class="pure-menu pure-menu-horizontal header">
    
    <ul class="level">
        <li class="level-item has-text-centered"><a href="#" class="link is-info"><strong>Pro Evo League</strong></a></li>
        <li class="level-item has-text-centered"><a href="@Url.Action("Create", "Authentication")" class="link is-info">Add User</a></li>
        <li class="level-item has-text-centered"><a href="@Url.Action("Create", "Event")" class="link is-info">Create Event</a></li>
        <li class="level-item has-text-centered"> <a href="@Url.Action("HeadToHead", "Records")" class="link is-info">Records</a></li>
    </ul>
</div>

ProEvoCanary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>
<body>
    <nav class="">
        @await Html.PartialAsync("_Header")
    </nav>
    <section class="section">
        <div class="container">
            @RenderBody()
        </div>
    </section>
</body>
</html>