ProEvoCanary.Web/Controllers/AuthenticationController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ProEvoCanary.DataAccess.Repositories.Interfaces;
using ProEvoCanary.Web.Models;

namespace ProEvoCanary.Web.Controllers
{
	public class AuthenticationController : Controller
	{
		private readonly IUserRepository _userRepository;

		public AuthenticationController(IUserRepository userRepository)
		{
			_userRepository = userRepository;
		}

		// GET: Authentication/Create
		public ActionResult Create()
		{
			return View("Create");
		}

		// POST: Authentication/Create
		[HttpPost]
		public ActionResult Create(CreateUserModel model)
		{
			if (ModelState.IsValid)
			{
				_userRepository.CreateUser(Guid.NewGuid(), model.Username, model.Forename, model.Surname,
					model.EmailAddress);
				return RedirectToAction("Index", "Default");
			}

			return View(model);
		}


	}
}

ProEvoCanary.Web/Views/Authentication/Create.cshtml
@model ProEvoCanary.Web.Models.CreateUserModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Authentication", FormMethod.Post))
{
    <div class="row">
        <div class="input-field col s12 m6">
            <label asp-for="Username"></label>
            <input type="text" asp-for="Username" placeholder="Enter your username" autocomplete="off"/>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m6">
            <label asp-for="EmailAddress"></label>
            <input type="text" asp-for="EmailAddress" placeholder="Enter your email Address" autocomplete="off"/>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m6">
            <label asp-for="Forename"></label>
            <input type="text" asp-for="Forename" placeholder="Enter your Forename" autocomplete="off"/>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12 m6">
            <label asp-for="Surname"></label>
            <input type="text" asp-for="Surname" placeholder="Enter your Surname" autocomplete="off" />

        </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Submit
            </button>
        </div>
    </div>

}